// packages/constructables/src/renderer.tsx
import { TickerCallback } from "@pixi/ticker";
import { Context, createMemo, JSX } from "solid-js";
import { createStore, SetStoreFunction } from "solid-js/store";
import { withContext } from "../utils/withContext";
import { createSolixiState, SxiContext } from "./store";
import { Constructable, SxiState } from "./types";

type Canvas = HTMLCanvasElement | OffscreenCanvas;

type SxiProviderProps<TCanvas extends Canvas> = {
  onCreated?: (state: SxiState) => void;
  state: SxiState;
  children: JSX.Element;
  rootElement: TCanvas;
}
const SxiProvider = <TCanvas extends Canvas>(props: SxiProviderProps<TCanvas>) => {
  return (
    <SxiContext.Provider value={props.state}>
      {props.children}
    </SxiContext.Provider/>
  );
}

export type SolixiRoot<TRootObject extends InstanceType<Constructable>, TContext> = {
  rootObject: TRootObject,
  state: TContext;
  setState: SetStoreFunction<TContext>;
  render: (props: { children: JSX.Element | JSX.Element[] }) => void;
}

/**
 * Creates a root object for the Constructables to add to.
 * @template TRootObject extends InstanceType<Constructable> - 
 * @template TContext - 
 * @param rootObject - 
 * @param context - 
 * @param contextValue - 
 * @param initialState - 
 * @returns 
 */
export const createRoot = <
  TRootObject extends InstanceType<Constructable>,
  TContext extends {}
>(
  rootObject: TRootObject,
  context: Context<TContext>,
  contextValue: TContext
): SolixiRoot<TRootObject, TContext> => {
  const [sxiState, setSxiState] = createStore(contextValue);

  const root: SolixiRoot<TRootObject, TContext> = {
    rootObject,
    state: sxiState,
    setState: setSxiState,
    render(props) {
      const childrenWithContext = createMemo(
        withContext(() => props.children, context, contextValue),
      );
    }
  }

  return root;
}

// packages/solixious/src/core2/renderer.tsx
import { createSolixiState, SxiContext } from "./store";
import { SxiState } from "./types";

type Canvas = HTMLCanvasElement | OffscreenCanvas;

type SxiProviderProps<TCanvas extends Canvas> = {
  onCreated?: (state: SxiState) => void;
  state: SxiState;
  children: JSX.Element;
  rootElement: TCanvas;
}
const SxiProvider = <TCanvas extends Canvas>(props: SxiProviderProps<TCanvas>) => {

  return (
    <SxiContext.Provider value={props.state}>
      {props.children}
    </SxiContext.Provider/>
  );
}


export type SolixiRootProps = {

}

export type SolixiRoot<TCanvas extends Canvas> = {
  state: SxiState;
  update: (props: SolixiRootProps) => SolixiRoot<TCanvas>;
}

const canvasToRootsLookup = new Map<Canvas, SolixiRoot<Canvas>>();

export const createRoot = <TCanvas extends Canvas>(canvas: TCanvas): SolixiRoot<TCanvas> => {
  // Check if createRoot has already been aclled on this element
  const prevRoot = canvasToRootsLookup.get(canvas);
  if (prevRoot) console.warn("Solixi.createRoot should only be called once!");

  const state = prevRoot?.state || createSolixiState();

  const root: SolixiRoot<TCanvas> = {
    state,
    update(props) {

    }
  }

  return root;
}
